CREATE TABLE IF NOT EXISTS cliente(
    id_cliente integer generated by default as identity primary key,
    nome varchar,
    email varchar,
    celular varchar,
    cpf varchar,
    cnpj varchar,
    data_nascimento varchar,
    tipo varchar
);
CREATE TABLE IF NOT EXISTS vendedor(
    id_vendedor integer generated by default as identity primary key,
    nome varchar,
    cpf varchar,
    data_nascimento varchar,
    email varchar,
    senha varchar
);
CREATE TABLE IF NOT EXISTS marca(
    id_marca integer generated by default as identity primary key,
    nome varchar,
    imagem text
);
CREATE TABLE IF NOT EXISTS modelo(
    id_modelo integer generated by default as identity primary key,
    nome varchar,
    id_marca integer,
    ano varchar,
    codigo_fipe varchar,
    numero_portas integer,
    numero_assentos integer,
    quilometragem real,
    possui_ar varchar
);
CREATE TABLE IF NOT EXISTS veiculo(
    id_veiculo integer generated by default as identity primary key,
    id_modelo integer,
    id_fornecedor integer,
    valor real,
    tipo varchar,
    cor varchar,
    placa varchar
);
CREATE TABLE IF NOT EXISTS agenda(
    id_agenda integer generated by default as identity primary key,
    id_vendedor integer,
    titulo varchar,
    descricao varchar,
    data_hora varchar
);
CREATE TABLE IF NOT EXISTS venda(
    id_venda integer generated by default as identity primary key,
    id_veiculo integer,
    id_cliente integer,
    id_vendedor integer,
    entrada real,
    parcelas integer,
    data varchar
);
CREATE TABLE promocao (
    id_promocao integer generated by default as identity primary key,
    id_veiculo integer,
    data_inicial varchar,
    data_final varchar,
    valor real
);
CREATE ROLE flutter_group;
CREATE ROLE flutter_role WITH LOGIN PASSWORD '123123';
GRANT flutter_group TO flutter_role;
GRANT SELECT,
    UPDATE,
    DELETE,
    INSERT ON ALL TABLES IN SCHEMA public TO flutter_group;